### ISSUE TITLE
Clangformat config file

### ISSUE THREAD

**Issue by krupitskas** [73s/Vorpal-Engine#22]

**Comment by MrDmitry** [comment]
﻿---
BasedOnStyle: Google
AlignAfterOpenBracket: DontAlign
AlignConsecutiveAssignments: 'false'
AlignConsecutiveDeclarations: 'false'
AlignOperands: 'false'
AlignTrailingComments: 'true'
AllowAllParametersOfDeclarationOnNextLine: 'true'
AllowShortBlocksOnASingleLine: 'false'
AllowShortCaseLabelsOnASingleLine: 'false'
AllowShortFunctionsOnASingleLine: Empty
AllowShortIfStatementsOnASingleLine: 'false'
AllowShortLoopsOnASingleLine: 'false'
AlwaysBreakBeforeMultilineStrings: 'false'
BinPackArguments: 'false'
BinPackParameters: 'false'
BreakBeforeBraces: Allman
BreakBeforeTernaryOperators: 'false'
BreakConstructorInitializersBeforeComma: 'true'
IndentCaseLabels: 'true'
IndentWidth: '4'
Language: Cpp
PointerAlignment: Left
SortIncludes: 'false'
SpaceAfterCStyleCast: 'true'
SpaceAfterTemplateKeyword: 'true'
SpaceBeforeAssignmentOperators: 'true'
SpaceBeforeParens: ControlStatements
SpaceInEmptyParentheses: 'false'
Standard: Cpp11
TabWidth: '4'
UseTab: Never

...
